[package]
name = "ipserver"
version = "0.1.1"
authors = ["maplebeats <maplebeats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.6.0"
log = "0.4.8"